### ISSUE TITLE
Revisioning turned my src or href attribute into "\undefined"

### ISSUE THREAD

**Issue by vimcaw** [hexojs/hexo-asset-pipeline#14]
Like this:
```html
<link rel="stylesheet" href="/undefined">
```

Terminal doesn't display any error.

After I disabled revisioning,  `src` or `href` attribute is right.

_config.yml: 
```yaml
asset_pipeline:
  revisioning:
    enable: true
```
