### ISSUE TITLE
Excluding Images

### ISSUE THREAD

**Issue by TheBeachMaster** [hexojs/hexo-asset-pipeline#52]
I am having a slight issue excluding images.

```yml
...
  imagemin:
    enable: true
   exclude: ['/path/to/image.png', '/path/to/another/image.png']
....
```

Does not work, images still get minified.

Use case, setting up PWA `manifest.json`  file `icons` entry.

Example [site](https://otienoken.me)

**Comment by B3rn475** [comment]
Hi TheBeachMaster are you using that exact syntax?
That is not valid `YAML`
What you want is probably:
```yaml
imagemin: 
  enable: true
  exclude: 
    - /path/to/image.png
    - /path/to/another/image.png
```
